# Generated by Django 3.2.7 on 2022-09-22 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagrat_grigorian', '0002_portfolio_tmp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio_tmp',
            name='cover',
        ),
        migrations.CreateModel(
            name='PortfolioImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='images/portfolio_tmp')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='bagrat_grigorian.portfolio_tmp')),
            ],
        ),
    ]
