# Generated by Django 3.2.7 on 2022-09-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagrat_grigorian', '0003_auto_20220922_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_tmp',
            name='description_futter',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio_tmp',
            name='description_numiration',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio_tmp',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
