# Generated by Django 3.2.7 on 2022-09-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagrat_grigorian', '0004_auto_20220923_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_tmp',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='portfolio_tmp',
            name='description_futter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='portfolio_tmp',
            name='description_numiration',
            field=models.TextField(),
        ),
    ]
