# Generated by Django 3.2.7 on 2022-10-02 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagrat_grigorian', '0005_auto_20220923_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, unique=True)),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioTmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_img', models.ImageField(upload_to='images/portfolio_tmp')),
                ('title', models.TextField()),
                ('date', models.TextField()),
                ('client', models.TextField()),
                ('category', models.TextField()),
                ('progect_url', models.URLField()),
                ('description', models.TextField()),
                ('description_numiration', models.TextField()),
                ('description_futter', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='tiles',
        ),
        migrations.AlterField(
            model_name='portfolioimg',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='bagrat_grigorian.portfoliotmp'),
        ),
        migrations.DeleteModel(
            name='portfolio_tmp',
        ),
    ]
