# Generated by Django 3.2.7 on 2022-10-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagrat_grigorian', '0006_auto_20221002_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliotmp',
            name='progect_url',
            field=models.URLField(blank=True),
        ),
    ]
