# Generated by Django 3.2.7 on 2022-10-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagrat_grigorian', '0007_alter_portfoliotmp_progect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotmp',
            name='name',
            field=models.TextField(null=True, unique=True),
        ),
    ]
